name: neural_rl
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  # Python
  - python=3.11

  # CUDA support
  - pytorch::pytorch-cuda=11.8
  - nvidia::cuda-cudart=11.8.89
  - nvidia::cuda-libraries=11.8.0
  - nvidia::cuda-runtime=11.8.0

  # PyTorch and related
  - pytorch::pytorch=2.4.1
  - pytorch::torchtriton=3.0.0

  # Scientific computing
  - numpy=1.26.4
  - scipy=1.12.0
  - pandas=2.2.1
  - scikit-learn=1.5.1

  # Visualization
  - matplotlib=3.8.3
  - matplotlib-base=3.9.2
  - seaborn=0.13.2

  # Jupyter and notebook support
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyterlab=4.2.5
  - notebook
  - ipython
  - ipykernel

  # Core utilities
  - pyyaml=6.0.1
  - tqdm=4.66.2
  - joblib=1.4.2
  - click=8.1.7
  - requests
  - certifi=2024.2.2
  - setuptools=75.1.0
  - pip=24.2

  # Math libraries
  - mkl=2023.1.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7

  # Additional tools
  - cloudpickle=3.0.0
  - appdirs=1.4.4
  - filelock=3.13.1
  - docker-pycreds=0.4.0

  # Pip packages
  - pip:
    - wandb==0.19.11
    - gymnasium==0.29.1
    - mujoco==2.3.7
    - torchdiffeq==0.2.4
    - farama-notifications==0.0.4
    - h5py==3.11.0
    - imageio==2.35.1
    - glfw==2.7.0
    - fire==0.6.0
    - protobuf==4.25.3
    - gitpython==3.1.42
    - absl-py==2.1.0

